var data = [
  {id: 1, name: 'Ted', surname: 'Smith', position: 'Java Developer', email: 'ted.smith@gmail.com', company: 'Electrical Systems', age: 30, education: 'High School Of Cambridge', knownledge: 'Java, Ruby'},
  {id: 2, name: 'Ed', surname: 'Johnson', position: 'C/C++ Market Data Developer', email: 'ed.johnson@gmail.com', company: 'Energy and Oil', age: 35, education: 'High School Of Cambridge', knownledge: 'C++'},
  {id: 3, name: 'Sam', surname: 'Williams', position: 'Technical Analyst', email: 'sam.williams@gmail.com', company: 'Airbus', age: 38, education: 'High School Of Cambridge', knownledge: ''},
  {id: 4, name: 'Alexander', surname: 'Brown', position: 'Project Manager', email: 'alexander.brown@gmail.com', company: 'Renault', age: 24, education: 'High School Of Cambridge', knownledge: ''},
  {id: 5, name: 'Nicholas', surname: 'Miller', position: 'Senior Software Engineer', email: 'nicholas.miller@gmail.com', company: 'Adobe', age: 33, education: 'High School Of Cambridge', knownledge: 'Unix, C/C++'},
  {id: 6, name: 'Andrew', surname: 'Thompson', position: 'Agile Project Manager', email: 'andrew.thompson@gmail.com', company: 'Google', age: 28, education: 'High School Of Cambridge', knownledge: ''},
  {id: 7, name: 'Ryan', surname: 'Walker', position: 'Application Support Engineer', email: 'ryan.walker@gmail.com', company: 'Siemens', age: 39, education: 'High School Of Cambridge', knownledge: 'ActionScript'},
  {id: 8, name: 'John', surname: 'Scott', position: 'Flex Developer', email: 'john.scott@gmail.com', company: 'Cargo', age: 45, education: 'High School Of Cambridge', knownledge: 'Flex'},
  {id: 9, name: 'James', surname: 'Phillips', position: 'Senior C++/C# Developer', email: 'james.phillips@gmail.com', company: 'Pro bugs', age: 30, education: 'High School Of Cambridge', knownledge: 'C/C++, Unix'},
  {id: 10, name: 'Brian', surname: 'Edwards', position: 'UNIX/C++ Developer', email: 'brian.edwards@gmail.com', company: 'IT Consultant', age: 23, education: 'High School Of Cambridge', knownledge: 'C/C++ Unix'},
  {id: 11, name: 'Jack', surname: 'Richardson', position: 'Ruby Developer', email: 'jack.richardson@gmail.com', company: 'Europe IT', age: 24, education: 'High School Of Cambridge', knownledge: 'Ruby'},
  {id: 12, name: 'Alex', surname: 'Howard', position: 'CSS3/HTML5 Developer', email: 'alex.howard@gmail.com', company: 'Cisco', age: 27, education: 'High School Of Cambridge', knownledge: 'CSS3/HTML5'},
  {id: 13, name: 'Carlos', surname: 'Wood', position: 'Node.js Developer', email: 'carlos.wood@gmail.com', company: 'HP', age: 36, education: 'High School Of Cambridge', knownledge: 'Node.js'},
  {id: 14, name: 'Adrian', surname: 'Russell', position: 'Frontend Developer', email: 'adrian.russell@gmail.com', company: 'Micro Systems', age: 31, education: 'High School Of Cambridge', knownledge: 'HTML, JavaScript'},
  {id: 15, name: 'Jeremy', surname: 'Hamilton', position: 'Scala Developer', email: 'jeremy.hamilton@gmail.com', company: 'Big Machines', age: 30, education: 'High School Of Cambridge', knownledge: 'Scala'},
  {id: 16, name: 'Ivan', surname: 'Woods', position: 'Objective C Developer', email: 'ivan.woods@gmail.com', company: '', age: 24, education: 'High School Of Cambridge', knownledge: 'Objective C'},
  {id: 17, name: 'Peter', surname: 'West', position: 'PHP/HTML Developer', email: 'peters.west@gmail.com', company: 'Adobe', age: 26, education: 'High School Of Cambridge', knownledge: 'PHP/HTML'},
  {id: 18, name: 'Scott', surname: 'Simpson', position: 'Designer', email: 'scott.simpson@gmail.com', company: 'IBM', age: 29, education: 'High School Of Cambridge', knownledge: 'Adobe PhotoShop'},
  {id: 18, name: 'Lorenzo', surname: 'Tucker', position: 'Architect', email: 'lorenzo.tucker@gmail.com', company: 'Intel', age: 29, education: 'High School Of Cambridge', knownledge: ''},
  {id: 19, name: 'Randy', surname: 'Grant', position: 'Engineer', email: 'randy.grant@gmail.com', company: 'Bridges', age: 30, education: 'High School Of Cambridge', knownledge: ''},
  {id: 20, name: 'Arthur', surname: 'Gardner', position: 'Analytic', email: 'arthur.gardner@gmail.com', company: 'Google', age: 31, education: 'High School Of Cambridge', knownledge: ''},
  {id: 21, name: 'Orlando', surname:'Ruiz', position: 'Unit Testing Developer', email: 'orlando.ruiz@gmail.com', company: 'Apple', age: 32, education: 'High School Of Cambridge', knownledge: ''},
  {id: 22, name: 'Ted', surname: 'Smith', position: 'Java Developer', email: 'ted.smith@gmail.com', company: 'Electrical Systems', age: 30, education: 'High School Of Cambridge', knownledge: 'Java, Ruby'},
  {id: 23, name: 'Ed', surname: 'Johnson', position: 'C/C++ Market Data Developer', email: 'ed.johnson@gmail.com', company: 'Energy and Oil', age: 35, education: 'High School Of Cambridge', knownledge: 'C++'},
  {id: 24, name: 'Sam', surname: 'Williams', position: 'Technical Analyst', email: 'sam.williams@gmail.com', company: 'Airbus', age: 38, education: 'High School Of Cambridge', knownledge: ''},
  {id: 25, name: 'Alexander', surname: 'Brown', position: 'Project Manager', email: 'alexander.brown@gmail.com', company: 'Renault', age: 24, education: 'High School Of Cambridge', knownledge: ''},
  {id: 26, name: 'Nicholas', surname: 'Miller', position: 'Senior Software Engineer', email: 'nicholas.miller@gmail.com', company: 'Adobe', age: 33, education: 'High School Of Cambridge', knownledge: 'Unix, C/C++'},
  {id: 27, name: 'Andrew', surname: 'Thompson', position: 'Agile Project Manager', email: 'andrew.thompson@gmail.com', company: 'Google', age: 28, education: 'High School Of Cambridge', knownledge: ''},
  {id: 28, name: 'Ryan', surname: 'Walker', position: 'Application Support Engineer', email: 'ryan.walker@gmail.com', company: 'Siemens', age: 39, education: 'High School Of Cambridge', knownledge: 'ActionScript'},
  {id: 29, name: 'John', surname: 'Scott', position: 'Flex Developer', email: 'john.scott@gmail.com', company: 'Cargo', age: 45, education: 'High School Of Cambridge', knownledge: 'Flex'},
  {id: 30, name: 'James', surname: 'Phillips', position: 'Senior C++/C# Developer', email: 'james.phillips@gmail.com', company: 'Pro bugs', age: 30, education: 'High School Of Cambridge', knownledge: 'C/C++, Unix'},
  {id: 31, name: 'Brian', surname: 'Edwards', position: 'UNIX/C++ Developer', email: 'brian.edwards@gmail.com', company: 'IT Consultant', age: 23, education: 'High School Of Cambridge', knownledge: 'C/C++ Unix'},
  {id: 32, name: 'Jack', surname: 'Richardson', position: 'Ruby Developer', email: 'jack.richardson@gmail.com', company: 'Europe IT', age: 24, education: 'High School Of Cambridge', knownledge: 'Ruby'},
  {id: 33, name: 'Alex', surname: 'Howard', position: 'CSS3/HTML5 Developer', email: 'alex.howard@gmail.com', company: 'Cisco', age: 27, education: 'High School Of Cambridge', knownledge: 'CSS3/HTML5'},
  {id: 34, name: 'Carlos', surname: 'Wood', position: 'Node.js Developer', email: 'carlos.wood@gmail.com', company: 'HP', age: 36, education: 'High School Of Cambridge', knownledge: 'Node.js'},
  {id: 35, name: 'Adrian', surname: 'Russell', position: 'Frontend Developer', email: 'adrian.russell@gmail.com', company: 'Micro Systems', age: 31, education: 'High School Of Cambridge', knownledge: 'HTML, JavaScript'},
  {id: 36, name: 'Jeremy', surname: 'Hamilton', position: 'Scala Developer', email: 'jeremy.hamilton@gmail.com', company: 'Big Machines', age: 30, education: 'High School Of Cambridge', knownledge: 'Scala'},
  {id: 37, name: 'Ivan', surname: 'Woods', position: 'Objective C Developer', email: 'ivan.woods@gmail.com', company: '', age: 24, education: 'High School Of Cambridge', knownledge: 'Objective C'},
  {id: 38, name: 'Peter', surname: 'West', position: 'PHP/HTML Developer', email: 'peters.west@gmail.com', company: 'Adobe', age: 26, education: 'High School Of Cambridge', knownledge: 'PHP/HTML'},
  {id: 39, name: 'Scott', surname: 'Simpson', position: 'Designer', email: 'scott.simpson@gmail.com', company: 'IBM', age: 29, education: 'High School Of Cambridge', knownledge: 'Adobe PhotoShop'},
  {id: 40, name: 'Lorenzo', surname: 'Tucker', position: 'Architect', email: 'lorenzo.tucker@gmail.com', company: 'Intel', age: 29, education: 'High School Of Cambridge', knownledge: ''},
  {id: 41, name: 'Randy', surname: 'Grant', position: 'Engineer', email: 'randy.grant@gmail.com', company: 'Bridges', age: 30, education: 'High School Of Cambridge', knownledge: ''},
  {id: 42, name: 'Arthur', surname: 'Gardner', position: 'Analytic', email: 'arthur.gardner@gmail.com', company: 'Google', age: 31, education: 'High School Of Cambridge', knownledge: ''},
  {id: 43, name: 'Orlando', surname:'Ruiz', position: 'Unit Testing Developer', email: 'orlando.ruiz@gmail.com', company: 'Apple', age: 32, education: 'High School Of Cambridge', knownledge: ''},
  {id: 44, name: 'Ted', surname: 'Smith', position: 'Java Developer', email: 'ted.smith@gmail.com', company: 'Electrical Systems', age: 30, education: 'High School Of Cambridge', knownledge: 'Java, Ruby'},
  {id: 45, name: 'Ed', surname: 'Johnson', position: 'C/C++ Market Data Developer', email: 'ed.johnson@gmail.com', company: 'Energy and Oil', age: 35, education: 'High School Of Cambridge', knownledge: 'C++'},
  {id: 46, name: 'Sam', surname: 'Williams', position: 'Technical Analyst', email: 'sam.williams@gmail.com', company: 'Airbus', age: 38, education: 'High School Of Cambridge', knownledge: ''},
  {id: 47, name: 'Alexander', surname: 'Brown', position: 'Project Manager', email: 'alexander.brown@gmail.com', company: 'Renault', age: 24, education: 'High School Of Cambridge', knownledge: ''},
  {id: 48, name: 'Nicholas', surname: 'Miller', position: 'Senior Software Engineer', email: 'nicholas.miller@gmail.com', company: 'Adobe', age: 33, education: 'High School Of Cambridge', knownledge: 'Unix, C/C++'},
  {id: 49, name: 'Andrew', surname: 'Thompson', position: 'Agile Project Manager', email: 'andrew.thompson@gmail.com', company: 'Google', age: 28, education: 'High School Of Cambridge', knownledge: ''},
  {id: 50, name: 'Ryan', surname: 'Walker', position: 'Application Support Engineer', email: 'ryan.walker@gmail.com', company: 'Siemens', age: 39, education: 'High School Of Cambridge', knownledge: 'ActionScript'},
  {id: 51, name: 'John', surname: 'Scott', position: 'Flex Developer', email: 'john.scott@gmail.com', company: 'Cargo', age: 45, education: 'High School Of Cambridge', knownledge: 'Flex'},
  {id: 52, name: 'James', surname: 'Phillips', position: 'Senior C++/C# Developer', email: 'james.phillips@gmail.com', company: 'Pro bugs', age: 30, education: 'High School Of Cambridge', knownledge: 'C/C++, Unix'},
  {id: 53, name: 'Brian', surname: 'Edwards', position: 'UNIX/C++ Developer', email: 'brian.edwards@gmail.com', company: 'IT Consultant', age: 23, education: 'High School Of Cambridge', knownledge: 'C/C++ Unix'},
  {id: 54, name: 'Jack', surname: 'Richardson', position: 'Ruby Developer', email: 'jack.richardson@gmail.com', company: 'Europe IT', age: 24, education: 'High School Of Cambridge', knownledge: 'Ruby'},
  {id: 55, name: 'Alex', surname: 'Howard', position: 'CSS3/HTML5 Developer', email: 'alex.howard@gmail.com', company: 'Cisco', age: 27, education: 'High School Of Cambridge', knownledge: 'CSS3/HTML5'},
  {id: 56, name: 'Carlos', surname: 'Wood', position: 'Node.js Developer', email: 'carlos.wood@gmail.com', company: 'HP', age: 36, education: 'High School Of Cambridge', knownledge: 'Node.js'},
  {id: 57, name: 'Adrian', surname: 'Russell', position: 'Frontend Developer', email: 'adrian.russell@gmail.com', company: 'Micro Systems', age: 31, education: 'High School Of Cambridge', knownledge: 'HTML, JavaScript'},
  {id: 58, name: 'Jeremy', surname: 'Hamilton', position: 'Scala Developer', email: 'jeremy.hamilton@gmail.com', company: 'Big Machines', age: 30, education: 'High School Of Cambridge', knownledge: 'Scala'},
  {id: 59, name: 'Ivan', surname: 'Woods', position: 'Objective C Developer', email: 'ivan.woods@gmail.com', company: '', age: 24, education: 'High School Of Cambridge', knownledge: 'Objective C'},
  {id: 60, name: 'Peter', surname: 'West', position: 'PHP/HTML Developer', email: 'peters.west@gmail.com', company: 'Adobe', age: 26, education: 'High School Of Cambridge', knownledge: 'PHP/HTML'},
  {id: 61, name: 'Scott', surname: 'Simpson', position: 'Designer', email: 'scott.simpson@gmail.com', company: 'IBM', age: 29, education: 'High School Of Cambridge', knownledge: 'Adobe PhotoShop'},
  {id: 62, name: 'Lorenzo', surname: 'Tucker', position: 'Architect', email: 'lorenzo.tucker@gmail.com', company: 'Intel', age: 29, education: 'High School Of Cambridge', knownledge: ''},
  {id: 63, name: 'Randy', surname: 'Grant', position: 'Engineer', email: 'randy.grant@gmail.com', company: 'Bridges', age: 30, education: 'High School Of Cambridge', knownledge: ''},
  {id: 64, name: 'Arthur', surname: 'Gardner', position: 'Analytic', email: 'arthur.gardner@gmail.com', company: 'Google', age: 31, education: 'High School Of Cambridge', knownledge: ''},
  {id: 65, name: 'Orlando', surname:'Ruiz', position: 'Unit Testing Developer', email: 'orlando.ruiz@gmail.com', company: 'Apple', age: 32, education: 'High School Of Cambridge', knownledge: ''},
  {id: 66, name: 'Ted', surname: 'Smith', position: 'Java Developer', email: 'ted.smith@gmail.com', company: 'Electrical Systems', age: 30, education: 'High School Of Cambridge', knownledge: 'Java, Ruby'},
  {id: 67, name: 'Ed', surname: 'Johnson', position: 'C/C++ Market Data Developer', email: 'ed.johnson@gmail.com', company: 'Energy and Oil', age: 35, education: 'High School Of Cambridge', knownledge: 'C++'},
  {id: 68, name: 'Sam', surname: 'Williams', position: 'Technical Analyst', email: 'sam.williams@gmail.com', company: 'Airbus', age: 38, education: 'High School Of Cambridge', knownledge: ''},
  {id: 69, name: 'Alexander', surname: 'Brown', position: 'Project Manager', email: 'alexander.brown@gmail.com', company: 'Renault', age: 24, education: 'High School Of Cambridge', knownledge: ''},
  {id: 70, name: 'Nicholas', surname: 'Miller', position: 'Senior Software Engineer', email: 'nicholas.miller@gmail.com', company: 'Adobe', age: 33, education: 'High School Of Cambridge', knownledge: 'Unix, C/C++'},
  {id: 71, name: 'Andrew', surname: 'Thompson', position: 'Agile Project Manager', email: 'andrew.thompson@gmail.com', company: 'Google', age: 28, education: 'High School Of Cambridge', knownledge: ''},
  {id: 72, name: 'Ryan', surname: 'Walker', position: 'Application Support Engineer', email: 'ryan.walker@gmail.com', company: 'Siemens', age: 39, education: 'High School Of Cambridge', knownledge: 'ActionScript'},
  {id: 73, name: 'John', surname: 'Scott', position: 'Flex Developer', email: 'john.scott@gmail.com', company: 'Cargo', age: 45, education: 'High School Of Cambridge', knownledge: 'Flex'},
  {id: 74, name: 'James', surname: 'Phillips', position: 'Senior C++/C# Developer', email: 'james.phillips@gmail.com', company: 'Pro bugs', age: 30, education: 'High School Of Cambridge', knownledge: 'C/C++, Unix'},
  {id: 75, name: 'Brian', surname: 'Edwards', position: 'UNIX/C++ Developer', email: 'brian.edwards@gmail.com', company: 'IT Consultant', age: 23, education: 'High School Of Cambridge', knownledge: 'C/C++ Unix'},
  {id: 76, name: 'Jack', surname: 'Richardson', position: 'Ruby Developer', email: 'jack.richardson@gmail.com', company: 'Europe IT', age: 24, education: 'High School Of Cambridge', knownledge: 'Ruby'},
  {id: 77, name: 'Alex', surname: 'Howard', position: 'CSS3/HTML5 Developer', email: 'alex.howard@gmail.com', company: 'Cisco', age: 27, education: 'High School Of Cambridge', knownledge: 'CSS3/HTML5'},
  {id: 78, name: 'Carlos', surname: 'Wood', position: 'Node.js Developer', email: 'carlos.wood@gmail.com', company: 'HP', age: 36, education: 'High School Of Cambridge', knownledge: 'Node.js'},
  {id: 79, name: 'Adrian', surname: 'Russell', position: 'Frontend Developer', email: 'adrian.russell@gmail.com', company: 'Micro Systems', age: 31, education: 'High School Of Cambridge', knownledge: 'HTML, JavaScript'},
  {id: 80, name: 'Jeremy', surname: 'Hamilton', position: 'Scala Developer', email: 'jeremy.hamilton@gmail.com', company: 'Big Machines', age: 30, education: 'High School Of Cambridge', knownledge: 'Scala'},
  {id: 81, name: 'Ivan', surname: 'Woods', position: 'Objective C Developer', email: 'ivan.woods@gmail.com', company: '', age: 24, education: 'High School Of Cambridge', knownledge: 'Objective C'},
  {id: 82, name: 'Peter', surname: 'West', position: 'PHP/HTML Developer', email: 'peters.west@gmail.com', company: 'Adobe', age: 26, education: 'High School Of Cambridge', knownledge: 'PHP/HTML'},
  {id: 83, name: 'Scott', surname: 'Simpson', position: 'Designer', email: 'scott.simpson@gmail.com', company: 'IBM', age: 29, education: 'High School Of Cambridge', knownledge: 'Adobe PhotoShop'},
  {id: 84, name: 'Lorenzo', surname: 'Tucker', position: 'Architect', email: 'lorenzo.tucker@gmail.com', company: 'Intel', age: 29, education: 'High School Of Cambridge', knownledge: ''},
  {id: 85, name: 'Randy', surname: 'Grant', position: 'Engineer', email: 'randy.grant@gmail.com', company: 'Bridges', age: 30, education: 'High School Of Cambridge', knownledge: ''},
  {id: 86, name: 'Arthur', surname: 'Gardner', position: 'Analytic', email: 'arthur.gardner@gmail.com', company: 'Google', age: 31, education: 'High School Of Cambridge', knownledge: ''},
  {id: 87, name: 'Orlando', surname:'Ruiz', position: 'Unit Testing Developer', email: 'orlando.ruiz@gmail.com', company: 'Apple', age: 32, education: 'High School Of Cambridge', knownledge: ''},
  {id: 88, name: 'Ted', surname: 'Smith', position: 'Java Developer', email: 'ted.smith@gmail.com', company: 'Electrical Systems', age: 30, education: 'High School Of Cambridge', knownledge: 'Java, Ruby'},
  {id: 89, name: 'Ed', surname: 'Johnson', position: 'C/C++ Market Data Developer', email: 'ed.johnson@gmail.com', company: 'Energy and Oil', age: 35, education: 'High School Of Cambridge', knownledge: 'C++'},
  {id: 90, name: 'Sam', surname: 'Williams', position: 'Technical Analyst', email: 'sam.williams@gmail.com', company: 'Airbus', age: 38, education: 'High School Of Cambridge', knownledge: ''},
  {id: 91, name: 'Alexander', surname: 'Brown', position: 'Project Manager', email: 'alexander.brown@gmail.com', company: 'Renault', age: 24, education: 'High School Of Cambridge', knownledge: ''},
  {id: 92, name: 'Nicholas', surname: 'Miller', position: 'Senior Software Engineer', email: 'nicholas.miller@gmail.com', company: 'Adobe', age: 33, education: 'High School Of Cambridge', knownledge: 'Unix, C/C++'},
  {id: 93, name: 'Andrew', surname: 'Thompson', position: 'Agile Project Manager', email: 'andrew.thompson@gmail.com', company: 'Google', age: 28, education: 'High School Of Cambridge', knownledge: ''},
  {id: 94, name: 'Ryan', surname: 'Walker', position: 'Application Support Engineer', email: 'ryan.walker@gmail.com', company: 'Siemens', age: 39, education: 'High School Of Cambridge', knownledge: 'ActionScript'},
  {id: 95, name: 'John', surname: 'Scott', position: 'Flex Developer', email: 'john.scott@gmail.com', company: 'Cargo', age: 45, education: 'High School Of Cambridge', knownledge: 'Flex'},
  {id: 96, name: 'James', surname: 'Phillips', position: 'Senior C++/C# Developer', email: 'james.phillips@gmail.com', company: 'Pro bugs', age: 30, education: 'High School Of Cambridge', knownledge: 'C/C++, Unix'},
  {id: 97, name: 'Brian', surname: 'Edwards', position: 'UNIX/C++ Developer', email: 'brian.edwards@gmail.com', company: 'IT Consultant', age: 23, education: 'High School Of Cambridge', knownledge: 'C/C++ Unix'},
  {id: 98, name: 'Jack', surname: 'Richardson', position: 'Ruby Developer', email: 'jack.richardson@gmail.com', company: 'Europe IT', age: 24, education: 'High School Of Cambridge', knownledge: 'Ruby'},
  {id: 99, name: 'Alex', surname: 'Howard', position: 'CSS3/HTML5 Developer', email: 'alex.howard@gmail.com', company: 'Cisco', age: 27, education: 'High School Of Cambridge', knownledge: 'CSS3/HTML5'},
  {id: 100, name: 'Carlos', surname: 'Wood', position: 'Node.js Developer', email: 'carlos.wood@gmail.com', company: 'HP', age: 36, education: 'High School Of Cambridge', knownledge: 'Node.js'},
  {id: 101, name: 'Adrian', surname: 'Russell', position: 'Frontend Developer', email: 'adrian.russell@gmail.com', company: 'Micro Systems', age: 31, education: 'High School Of Cambridge', knownledge: 'HTML, JavaScript'},
  {id: 102, name: 'Jeremy', surname: 'Hamilton', position: 'Scala Developer', email: 'jeremy.hamilton@gmail.com', company: 'Big Machines', age: 30, education: 'High School Of Cambridge', knownledge: 'Scala'},
  {id: 103, name: 'Ivan', surname: 'Woods', position: 'Objective C Developer', email: 'ivan.woods@gmail.com', company: '', age: 24, education: 'High School Of Cambridge', knownledge: 'Objective C'},
  {id: 104, name: 'Peter', surname: 'West', position: 'PHP/HTML Developer', email: 'peters.west@gmail.com', company: 'Adobe', age: 26, education: 'High School Of Cambridge', knownledge: 'PHP/HTML'},
  {id: 105, name: 'Scott', surname: 'Simpson', position: 'Designer', email: 'scott.simpson@gmail.com', company: 'IBM', age: 29, education: 'High School Of Cambridge', knownledge: 'Adobe PhotoShop'},
  {id: 106, name: 'Lorenzo', surname: 'Tucker', position: 'Architect', email: 'lorenzo.tucker@gmail.com', company: 'Intel', age: 29, education: 'High School Of Cambridge', knownledge: ''},
  {id: 107, name: 'Randy', surname: 'Grant', position: 'Engineer', email: 'randy.grant@gmail.com', company: 'Bridges', age: 30, education: 'High School Of Cambridge', knownledge: ''},
  {id: 108, name: 'Arthur', surname: 'Gardner', position: 'Analytic', email: 'arthur.gardner@gmail.com', company: 'Google', age: 31, education: 'High School Of Cambridge', knownledge: ''},
  {id: 109, name: 'Orlando', surname:'Ruiz', position: 'Unit Testing Developer', email: 'orlando.ruiz@gmail.com', company: 'Apple', age: 32, education: 'High School Of Cambridge', knownledge: ''}
];

var app = angular.module('myApp', ['fancygrid-angularjs']);

app.controller('MainController', function($scope, $interval, $compile){
  $scope.config = {
    width: 600,
    height: 400,
    data: data,
    disableModuleLoad: true,
    defaults: {
      type: 'string',
      width: 100,
      sortable: true,
      resizable: true
    },
    columns: [{
      index: 'id',
      title: 'Id',
      //locked: true,
      width: 50,
      type: 'number'
    },{
      index: 'company',
      title: 'Company'
    },{
      index: 'name',
      title: 'Name'
    },{
      index: 'surname',
      title: 'Sur Name'
    },{
      index: 'age',
      title: 'Age',
      type: 'number'
    },{
      index: 'education',
      title: 'Education',
      width: 150
    },{
      index: 'knownledge',    
      title: 'Knownledge',
      width: 100
    },{
      index: 'position',
      title: 'Position',
      width: 100
    }]
  };
});